//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Medium
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        [DisplayName("Date Updated")]
        public Nullable<System.DateTime> datetime { get; set; }
    }
}
